### ISSUE TITLE
Y appears to be Up in the example

### ISSUE THREAD

**Issue by alice-i-cecile** [ManevilleF/hexx#10]
The Bevy ecosystem uses Z-up by convention.

**Comment by alice-i-cecile** [comment]
Meshes appear to be generate Y up as well.

**Comment by ManevilleF** [comment]
Are you sure? https://bevy-cheatbook.github.io/features/coords.html

**Comment by alice-i-cecile** [comment]
Nope, I'm wrong about the standard conventions :)
