### ISSUE TITLE
Column mesh normals aren't normalized

### ISSUE THREAD

**Issue by Netzwerk2** [ManevilleF/hexx#108]
**Describe the bug**
The normals generated by `ColumnMeshBuilder` are not unit vectors.

**To Reproduce**
```rs
use hexx::{ColumnMeshBuilder, HexLayout};

fn main() {
    let mesh_info = ColumnMeshBuilder::new(&HexLayout::default(), 1.0).build();

    for normal in mesh_info.normals {
        println!("{}", normal.length());
    }
}

```

**Expected behavior**
All normals should be of length 1.

**Screenshots Or Code snippet**
<details>
<summary>Actual output</summary>

```
1.7320508
1.7320508
1.7320508
1.7320508
1.7320509
1.7320509
1.7320509
1.7320509
1.7320508
1.7320508
1.7320508
1.7320508
1.7320508
1.7320508
1.7320508
1.7320508
1.7320509
1.7320509
1.7320509
1.7320509
1.7320508
1.7320508
1.7320508
1.7320508
1
1
1
1
1
1
1
1
1
1
1
1
1
1
```
</details>

**Comment by ManevilleF** [comment]
Nice catch, that should be easy enough to fix soon.

What are the consequences of this? Is the lighting affected ?

**Comment by Netzwerk2** [comment]
I didn't test it, but yes it should affect lighting in bevy.

In my case I want to reflect a vector with respect to the normal, which gives wrong results if the normal isn't a unit vector.

**Comment by ManevilleF** [comment]
@alice-i-cecile Have you noticed lighting issues in Emergence ? Does #109 bring any visual change to the game ?

**Comment by ManevilleF** [comment]
@Netzwerk2 Could you check if #109 fixes the issue for you ?

**Comment by Netzwerk2** [comment]
Yes, it works as expected now.
