### ISSUE TITLE
How to use ColorMesh2dBundle with textures

### ISSUE THREAD

**Issue by gmoller** [ManevilleF/hexx#117]
**Is your feature request related to a problem? Please describe.**
How do I go about using textures for the hexes in the ColorMesh2dBundle?

**Describe the solution you'd like**
I'd like to use textures instead of plain colors for the hexes.

**Describe alternatives you've considered**
I've tried the following:

```rust
let texture_handle = asset_server.load("Ocean1.png");
let foo = materials.add(ColorMaterial::from(texture_handle));

let entity = commands
                .spawn(ColorMesh2dBundle {
                    mesh: mesh.clone().into(),
                    foo.clone(),
                    transform: Transform::from_xyz(pos.x, pos.y, 0.0).with_scale(Vec3::splat(1.)),
                    ..default()
                })
                .id();
```

**Comment by ManevilleF** [comment]
This is not `hexx` related but [bevy](https://github.com/bevyengine/bevy) related. `hexx`  does not interact directly with bevy, but provides a `MeshInfo` util struct to generate bevy mesh (see examples or README).

The [ColorMaterial](https://docs.rs/bevy/latest/bevy/sprite/struct.ColorMaterial.html) supports textures so there should not be a problem.

Make sure that in your snippet:
- `mesh` is a `Handle<Mesh>` added to the `Assets<Mesh>` pointing to your hexagon plane/column
- replace the following:
```diff
- foo.clone(),
+ material: foo.clone(),
```

And I think it should work
