### ISSUE TITLE
Example showing how to use sprite sheet for animated tiles

### ISSUE THREAD

**Issue by feelingsonice** [ManevilleF/hexx#124]
**Is your feature request related to a problem? Please describe.**
I'm relatively new to Bevy and I'd love to use `hexx` for my hex grid tilemap. I'd looking to animate the tiles with sprite sheets but don't have any examples to go off of. It seems like the library is tightly integrated with using meshes from what I can tell from the examples.

**Describe the solution you'd like**
Pointers or code examples to how one could use `hexx` along with sprite sheets.

**Describe alternatives you've considered**
Considered using `bevy_ecs_tilemap` but not sure if the hex grid management there is right for me.

**Comment by ManevilleF** [comment]
`hexx` is a coordinate library, if you don't want to use the mesh generation and instead use sprite sheets it's fine !
All that matters are the world space coordinates, so you can skip the mesh part, use a sprite sheet bundle, and keep the `Transform` values like in the example.

I can make an example, but I need to find a free to use hexagon sprite sheet

**Comment by ManevilleF** [comment]
@feelingsonice Could you check #135 ?
