### ISSUE TITLE
Add `Direction::angle` method

### ISSUE THREAD

**Issue by alice-i-cecile** [ManevilleF/hexx#14]
This method should return the standard angle in radians (counterclockwise from +x) associated with the center of each direction.

This is helpful in concert with #13 to support discretized object and camera rotation.

**Comment by ManevilleF** [comment]
That would make a great addition !
As context there is a similar functionality in [hex_layout](https://github.com/ManevilleF/hexx/blob/main/src/layout.rs#L45) computing the corners of hexagons, and I note that in your example the `start_rotation`is missing (flat/pointy hexagons)
