### ISSUE TITLE
Pointy Top and Flat Top EdgeDirections are swapped

### ISSUE THREAD

**Issue by msparkles** [ManevilleF/hexx#161]
This broke our game using the library.

According to https://www.redblobgames.com/grids/hexagons/ ...
![image](https://github.com/ManevilleF/hexx/assets/33348966/e795d01e-48eb-4bc4-a8c3-c550193c2168)

Yet...

```
    /// Direction to (1, -1)
    ///
    /// Represents "Top right" edge in flat orientation
    pub const FLAT_TOP_RIGHT: Self = Self(5);
```

**Comment by ManevilleF** [comment]
The screenshot is of pointy orientation, what is the expected behaviour?

**Comment by msparkles** [comment]
The FLAT_TOP_RIGHT direction has (supposedly, according to the docs) the value of POINTY_TOP_RIGHT

**Comment by msparkles** [comment]
As in, looking at the hexagon guide, it seems that 1, -1 should be *pointy's top right*, not flat's

**Comment by ManevilleF** [comment]
Thanks for noticing this, I guess I got confused by all const variants. Could you review #162 ? I'll release a fix afterwards

**Comment by msparkles** [comment]
We're bad at the math ourselves :P We only know if our game works or not. For a patch for our game we just used values directly from the article, if you want someone to review the math you'll need someone else....
