### ISSUE TITLE
Add function to compute (rounded) center of group of hexagons

### ISSUE THREAD

**Issue by alice-i-cecile** [ManevilleF/hexx#17]
This is useful when working with e.g. copy-paste functionality.

The code for this not trivial, especially if you want to avoid accidental overflows.

**Comment by alice-i-cecile** [comment]
A snippet from my code:

```rust
        if self.is_empty() {
            return;
        }

        // FIXME: this naive center calculation will overflow
        let mut sum_x = 0;
        let mut sum_y = 0;

        for tile_pos in self.keys() {
            sum_x += tile_pos.x as usize;
            sum_y += tile_pos.x as usize;
        }

        let center = TilePos {
            hex: Hex {
                x: (sum_x / self.len()) as i32,
                y: (sum_y / self.len()) as i32,
            },
        };
```

Can still overflow, but not as easily. Ideally you'd do a proper iterative approach that never requires storing the final sum.

**Comment by alice-i-cecile** [comment]
See https://www.heikohoffmann.de/htmlthesis/node134.html for such an algorithm.

**Comment by alice-i-cecile** [comment]
Median should also be added, and will generally be about as good and significantly faster / simpler. Use the quickselect algorithm!

**Comment by alice-i-cecile** [comment]
Median snippet (my code above overflowed quickly 😂):

```rust
        if self.is_empty() {
            return;
        }

        let mut x_vec = Vec::from_iter(self.keys().map(|tile_pos| tile_pos.x));
        let mut y_vec = Vec::from_iter(self.keys().map(|tile_pos| tile_pos.y));

        x_vec.sort_unstable();
        y_vec.sort_unstable();

        let mid = self.len() / 2;
        let center = TilePos {
            hex: Hex {
                x: x_vec[mid],
                y: y_vec[mid],
            },
        };
```

**Comment by ManevilleF** [comment]
Could you give a precise use case for this ? I'm not sure I understand.

Is it like:
```rust
fn find_center_of(coords: &[Hex]) -> Hex {
     // returns the center of the given coords
} 
```

**Comment by alice-i-cecile** [comment]
That's the sort of API I'd like to see, although over a general iterator of hexes.

In my case, I'm using it to center a selection of structures that I've added to my clipboard, so then they aren't bizarrely offset :)

**Comment by nuggetInc** [comment]
> A snippet from my code:
> 
> ```rust
>         if self.is_empty() {
>             return;
>         }
> 
>         // FIXME: this naive center calculation will overflow
>         let mut sum_x = 0;
>         let mut sum_y = 0;
> 
>         for tile_pos in self.keys() {
>             sum_x += tile_pos.x as usize;
>             sum_y += tile_pos.x as usize;
>         }
> 
>         let center = TilePos {
>             hex: Hex {
>                 x: (sum_x / self.len()) as i32,
>                 y: (sum_y / self.len()) as i32,
>             },
>         };
> ```
> 
> Can still overflow, but not as easily. Ideally you'd do a proper iterative approach that never requires storing the final sum.

Looking at this code I noticed that doesn’t necessarily compute the center, but computes the average of all the hexes (which is still useful).

The algorithm for calculating the center of all the hexes is a lot more trivial:
```rust
fn find_center_of(hexes: impl Iterator<Item = Hex>) -> Hex {
    let mut x_min = 0;
    let mut y_max = 0;
    let mut x_min = 0;
    let mut y_max = 0;
    
    for hex in hexes {
        x_min = x_min.min(hex.x);
        x_max = x_min.max(hex.x);
        y_min = y_min.min(hex.y);
        y_max = y_min.max(hex.y);
    }
    
    let x = (x_min + x_max) / 2;
    let y = (y_min + y_max) / 2;
    
    Hex::new(x, y)
}
```

A few notes about this implementation:
- I made it without compiling or an editor (expect copy paste errors) but I think the idea should be clear.
- This will return `hex::ZERO` instead of `None` when `hexes` is an empty iterator (This was easier to write), but it should be fairly easy to change this.
- This only has overflowing issues when the `length` of exceeds `i32::MAX / 2`.

These 3 methods (`center`, `average` and `median`) should probably give pointers to each other in their documentation.

**Comment by alice-i-cecile** [comment]
> This only has overflowing issues when the length of exceeds i32::MAX / 2.

You should be able to fix even that by dividing first, and then adding.

**Comment by ManevilleF** [comment]
So something like:

```rust
let average = Hex::ZERO.range(10).avg();
let center = Hex::ZERO.range(10).center();
```

Directly for iterators ?

**Comment by alice-i-cecile** [comment]
Yes that's lovely! And you even get to group them nicely with a trait.

**Comment by ManevilleF** [comment]
I can't implement a `median` operation since I can't sort the coordinates
