### ISSUE TITLE
Wrap-around map

### ISSUE THREAD

**Issue by f-hoenix** [ManevilleF/hexx#175]
Hello!
I see you've added the concept of maps to the crate with the HexagonalMap structure!
Any plan to add support for wrap-around maps? Hexagonal maps where the left-most tiles are adjacent to the right-most tiles
(Or top and bottom)

**Comment by ManevilleF** [comment]
The concept already exists, and there is a dedicated example to showcase the feature. Is there something missing for your usage?

**Comment by f-hoenix** [comment]
Nice!
I didn't remember it existed and didn't look again 🤦‍♂️
