### ISSUE TITLE
About OffsetHexMode

### ISSUE THREAD

**Issue by lishaoxia1985** [ManevilleF/hexx#178]
In the redblobgames.com, it seems that Pointy hex used EvenRows and OddRows, in the other way Flat hex used EvenColumns and OddColumns.
That means we only need to define an Enum like this:
```
OffsetHexMode {
Odd,
Even,
}
```

**Comment by ManevilleF** [comment]
Hi @lishaoxia1985 , thanks for the issue. Good catch, I'll think about a good solution to avoid the confusion, either integrate the orientation in the conversion or have explicit docs

**Comment by ManevilleF** [comment]
@lishaoxia1985 could you review #189 ?

**Comment by lishaoxia1985** [comment]
Maybe good

**Comment by lishaoxia1985** [comment]
Do you think Rows and Columns is necessary?

**Comment by ManevilleF** [comment]
Yeah It might not make sense, just changed it in the PR

**Comment by lishaoxia1985** [comment]
And we should add the necessary comment to describe.
