### ISSUE TITLE
lib.rs bevy usage doctest fails to compile

### ISSUE THREAD

**Issue by ManevilleF** [ManevilleF/hexx#183]
**Describe the bug**

CI Output from #181 :
```
---- src/lib.rs - (line 200) stdout ----
Test executable failed (exit status: 127).

stderr:
/tmp/rustdoctestu5iSe3/rust_out: error while loading shared libraries: libstd-ca74a2d9c5166d9f.so: cannot open shared object file: No such file or directory
```

**To Reproduce**
Remove the `ignore` flag from the doctest

**Expected behavior**
Should compile and run successfully

**Comment by bas-ie** [comment]
Yeah, this is also affecting Bevy main repo so I'll go look if anyone's sorted it yet :eyes:

**Comment by bas-ie** [comment]
Got it, that's a weird one. Fix inc.
