### ISSUE TITLE
`EdgeDirection::unit_vector` is Y flipped?

### ISSUE THREAD

**Issue by MatrixDev** [ManevilleF/hexx#186]
**Describe the bug**
I'm using `unit_vector` to rotate objects in the hex. But it seams that `Y` component of this vector is always flipped.

**To Reproduce**
Here is a simple test, that calculates direction manually vs `unit_vector`:
```rust
let layout = HexLayout::default();
for direction in EdgeDirection::ALL_DIRECTIONS {
    let h0 = hex(0, 0);
    let h1 = h0.neighbor(direction);

    let h0pos = layout.hex_to_world_pos(h0);
    let h1pos = layout.hex_to_world_pos(h1);

    let look_to_test = (h1pos - h0pos).normalize();
    let look_to = direction.unit_vector(layout.orientation);

    println!("{look_to_test} vs {look_to}");
}
```

And here are results:
```
[0.8660254,   -0.49999997] vs [0.8660254,          0.5]
[0,           -0.99999994] vs [-0.00000004371139,  1]
[-0.8660254,  -0.49999997] vs [-0.8660254,         0.50000006]
[-0.8660254,   0.49999997] vs [-0.8660253,        -0.5000002]
[0,            0.99999994] vs [0.000000011924881, -1]
[0.8660254,    0.49999997] vs [0.86602527,        -0.5000002]
```

As you can see `Y` component is always flipped, while `X` is always the same (excluding rounding errors)

**Expected behavior**
`unit_vector` should return a direction to a neighbor hex.

**Screenshots Or Code snippet**
Provided above.

**Comment by ManevilleF** [comment]
Nice catch, I'll write some tests to reproduce this behaviour and propose a fix asap

**Comment by ManevilleF** [comment]
Okay so this was not a really bug but due to `HexLayout` having its `Y` axis *inverted*  by default

**Comment by MatrixDev** [comment]
> Okay so this was not a really bug but due to `HexLayout` having its `Y` axis _inverted_ by default

But what does it represent than? Souldn't `hex_to_world_pos` also have `Y` flipped?

**Comment by ManevilleF** [comment]
`hex_to_world_pos` is a method of `HexLayout`, so it had the inverted axis. The PR I opened changes this behaviour to have the default layout uninverted, matching methods like angle and unit vector computations outside of the layout.
You may review #187

**Comment by ManevilleF** [comment]
`unit_vector` is not in world space. It doesn't know about:
- The size of the hexagons
- The axis scales
- The world origin
- etc

Therefore to be applied in world space transformations are needed. `HexLayout` could provide such transformations if you want to avoid doing the normalized world space operations
