### ISSUE TITLE
Add more iterator tools

### ISSUE THREAD

**Issue by ManevilleF** [ManevilleF/hexx#33]
- `rotated_by`
- `rotated_left_by`
- `rotated_right_by`
- `rotated_left`
- `rotated_left`
- `inverted`: to apply `Neg` to all elements
- `bounds`: to find the centroid and range containing the entire iterator

**Comment by alice-i-cecile** [comment]
Probably "bounds", right?

**Comment by ManevilleF** [comment]
After investigation, the cost of implementing this might exceed its value
