### ISSUE TITLE
Add method to report cubic coordinates

### ISSUE THREAD

**Issue by alice-i-cecile** [ManevilleF/hexx#41]
These can be useful for various algorithms, or more intuitive to report to users.

I was thinking `hex.as_cubic()`.

**Comment by ManevilleF** [comment]
`Hex` provides the `z` getter and a `to_array3` for this purpose. What would you want to see? A conversion to `glam::IVec3` ?

**Comment by alice-i-cecile** [comment]
Ah, `to_array3` was the method I was missing. Perhaps either rename it or add a doc alias?

**Comment by alice-i-cecile** [comment]
A converting directly into `IVec3` would be slightly more convenient though.

**Comment by ManevilleF** [comment]
Did you check `Hexx::as_ivec3` ?
