### ISSUE TITLE
Bevy Camera2dBundle Support

### ISSUE THREAD

**Issue by andrewexton373** [ManevilleF/hexx#64]
I'm trying to integrate this library into a current project that's working with a Camera2d Bundle with Bevy. After some fumbling, I tried changing the Camera3dBundle in the hex_grid example to a Camera2dBundle and discovered that this broke the example. Is this expected behavior? Is Bevy's Camera2dBundle supported?

**Describe the solution you'd like**
Support the Camera2dBundle for Bevy.

**Describe alternatives you've considered**
Using Camera3dBundle instead of Camera2dBundle for Bevy.

**Comment by ManevilleF** [comment]
You can use a `Camera2dBundle` but then you need to use 2d meshes ( `MaterialMesh2dBundle` instead of `PbrBundle`)

**Comment by andrewexton373** [comment]
I appreciate the quick response, I just got the hex_grid example working with the Camera2dBundle with this advice! It required switching the `StandardMaterial` for `ColorMaterial`, but with that I was able to get it working. Let me know if it would be good to have an example on this use case, I know I was stumped for a bit. I'd be glad to assist in putting a PR together.
