### ISSUE TITLE
Implement Serialize, Deserialize, Reflect and FromReflect for Hex

### ISSUE THREAD

**Issue by alice-i-cecile** [ManevilleF/hexx#70]
**Is your feature request related to a problem? Please describe.**

I want to implement serde and reflection on my new-typed Hex component.

I can't derive this, because Hex doesn't impl these traits.

**Describe the solution you'd like**

Implement these traits, guarded by two distinct feature flags that are off by default.

**Describe alternatives you've considered**

I can probably get around this with a remote derive or a manual implementation?

**Comment by alice-i-cecile** [comment]
Workaround was implemented here: <https://github.com/Leafwing-Studios/Emergence/pull/646/commits/cd443266aa09308670a81556a2f7d42761921e44>

**Comment by ManevilleF** [comment]
`hexx` provides a `ser_de` feature. If you enable it `Hex` and other types will derive `Serialize` and `Deserialize`
