### ISSUE TITLE
Better mesh generation

### ISSUE THREAD

**Issue by ManevilleF** [ManevilleF/hexx#77]
**Is your feature request related to a problem? Please describe.**

The current hexagonal planes and columns API is straightforward but lacks customization and the code is hard to maintain

**Describe the solution you'd like**

- Implement a `MeshBuilder` with various options like rotation , offset, height, subdivisions, etc.
- Add a mesh builder example to showcase the customization

**Additional context**

@alice-i-cecile identified some rendering issues with the partial columns and this refactoring should attempt to fix it

**Comment by alice-i-cecile** [comment]
Mesh merging is another big feature on my wishlist here! I would love to have this handled for me out of the box, although I suspect that's optimally integrated with a chunking system 🤔
