### ISSUE TITLE
Repeated use of `mesh` in example is unclear

### ISSUE THREAD

**Issue by alice-i-cecile** [ManevilleF/hexx#8]
https://github.com/ManevilleF/hexx/blob/767a99c57632e457e87118c8968fcffc16f15943/examples/hex_grid.rs#L61

With type-hints on, it's clear what's going on here: the first usage is a `Mesh`, the latter is a `Handle<Mesh>`. Reusing the same name makes it hard to quickly understand this important distinction.

**Comment by ManevilleF** [comment]
Good catch !
