### ISSUE TITLE
Implement PartialEq for HexDirection

### ISSUE THREAD

**Issue by GuimilXD** [ManevilleF/hexx#83]
**Is your feature request related to a problem? Please describe.**
I'd like to create an `egui` slider that controls the `HexOrientation` of a hex map.

**Describe the solution you'd like**
I'd like to `HexOrientation` to implement `PartialEq` and possibly other common traits.

**Describe alternatives you've considered**
I've created an enum that implemented `Into<HexOrientation>`, but found the bodge to be just ugly. 

**Additional context**
![image](https://user-images.githubusercontent.com/60893025/236967929-44a8ab60-3717-497f-84d2-3a6cd9690078.png)

**Comment by GuimilXD** [comment]
So, is it ok if I pull request a quick fix? I just need it to be working ASAP. In the future I might even try to implement the enum version and PR that.

**Comment by alice-i-cecile** [comment]
Yes, please feel free!
