### ISSUE TITLE
Implement bevy reflect traits

### ISSUE THREAD

**Issue by killercup** [ManevilleF/hexx#98]
**Is your feature request related to a problem? Please describe.**
I wanted to see/edit hexx components using bevy-inspector-egui and saw that they don't implement `bevy::Reflect`.

**Describe the solution you'd like**
Add a feature flag to add the trait derives.

**Additional context**
I made [this super tiny commit](https://github.com/killercup/hexx/commit/50b874f483f9cb32083ed653b80e6a79ac3c3dfb) a while ago for the previous version but never turned it into a PR. You're welcome to take this diff and use it as you see fit, consider it public domain. Maybe I have time to look at it again in a couple weeks :)

**Comment by uvizhe** [comment]
Hey, I'm going to PR this as I need this feature right now. Will `reflect` feature name be suitable?

**Comment by ManevilleF** [comment]
> Hey, I'm going to PR this as I need this feature right now. Would `reflect` feature name be suitable?

I'd say `bevy_reflect` is better like:

```toml
bevy_reflect = ["dep:bevy_reflect"]
```

**Comment by uvizhe** [comment]
BTW, I was going to add Reflect to Hex only. Not sure if it's enough, tho.

**Comment by ManevilleF** [comment]
> BTW, I was going to add Reflect to Hex only. Not sure if it's enough, tho.

I think you should also add it to `Direction`, `DiagonalDirection`, `HexBounds` and `HexLayout`
